### PR TITLE
localized JS, text-domains, minor stuff

### PR DESCRIPTION
**Pull request by m0n0mind**
Add localized JS
Fix function name for JS close handling
add text-domains, etc...

### CODE REVIEW

**Comment by ahebrank** [comment]
It's hard for me to see the merge completely--can I get you to merge from my HEAD and resubmit?

**Comment by m0n0mind** [comment]
hey, i'm still fiddling to get used to the github.com interface, but i'll try ;)

**Comment by m0n0mind** [comment]
ok, guess i rather abused the github UI now by separating every file change into a separate branch. doh!
oh well, but at least it should now be easy to automatically merge the changes into your head branch.

**Comment by ahebrank** [comment]
No problem.  I'll merge the patches locally, test and then add them in.  Thanks!

**Comment by m0n0mind** [comment]
great!

**Pull request closed without merging**
